# wrangler.toml
name = "tele-upload-bot"
main = "tele-upload.js"
compatibility_date = "2025-01-01"

# KV untuk menyimpan state percakapan & folder default user
[[kv_namespaces]]
binding = "SESSIONS"
id = "74cf9da380d544adb807ef5a38b36aec"
